### ISSUE TITLE
how to build refgene.mat file

### ISSUE THREAD

**Issue by sbamin** [sbamin/canine_gistic2#5]
GISTIC2 requires refgene.mat, e.g., [hg19.mat](ftp://ftp.broadinstitute.org/pub/GISTIC2.0/) file. How do I create it for non-human genomes?

**Comment by sbamin** [comment]
refgene.mat is a matlab array file which in turn contains three sub-array files.

>Screenshots here are from _hg19.mat_ file[1] which you can load into matlab using following command:

```
load('hg19.mat')
```

## cyto

This is 1xN matlab [struct array](https://www.mathworks.com/help/releases/R2019a/matlab/ref/struct.html?container=jshelpbrowser) with six fields. N is number of cytobands for all canonical chromosomes, e.g., 22, X, Y for hg19.

It contains cytoband information. You can get cytoband from UCSC table browser or UCSC goldenPath archive for the respective genome-version, e.g., For canFam3, https://link.sbamin.com/2ztpbWM or http://hgdownload.soe.ucsc.edu/goldenPath/canFam3/database/cytoBandIdeo.txt.gz

Note that not all cytoband/Ideogram tables are as detailed as hg19. GISTIC2 may required short (p) and long (q) arm annotations in the `name` column for calculating arm-level copy-number changes, e.g., 1p, 2q, etc. but it's ok if you do not have detailed annotations as in hg19.mat

![Screenshot 2020-06-26 17 32 08](https://user-images.githubusercontent.com/12156027/85904004-bd4bcd00-b7d5-11ea-94a1-feab0e1791d5.png)

Note that `chrn` is a numeric vector for corresponding `chr` character vector, i.e., X is renamed as 23, and Y as 24, and serves as a linker to _rg_ array below.

![Screenshot 2020-06-26 17 55 41](https://user-images.githubusercontent.com/12156027/85904346-7b6f5680-b7d6-11ea-9e2a-3300712ba9f3.png)

## rg

This is an actual refgene.mat with detailed gene annotations. It is 1xP matlab struct array with 12 fields. P is number of **unique** genes within  all of canonical chromosomes from `chrn` column of _cyto_ array, e.g., 22, 23 (X) and 24(Y) for hg19.

You can use genome-version specific gene annotation file, e.g. refGene or Ensembl or GENCODE gtf, to prepare _rg_ file with following columns:

![Screenshot 2020-06-26 17 32 26](https://user-images.githubusercontent.com/12156027/85904791-a3ab8500-b7d7-11ea-819c-d57e8b5a89d7.png)

## rg_info

This is 1x1 matlab struct array with eight fields. It contains software metadata and is not required to run gistic2 but required to [compile updated `gp_gistic2_from_seg` executable script](https://github.com/sbamin/canine_gistic2). 

![Screenshot 2020-06-26 17 32 40](https://user-images.githubusercontent.com/12156027/85903279-f4b97a00-b7d3-11ea-972a-e461b3ac823e.png)

***

You can prepare above array files as tab or comma separated tables, and [import into matlab](https://www.mathworks.com/matlabcentral/answers/72545-how-to-import-csv-file-in-matlab) as three separate arrays, e.g., cyto, rg, and rg_info.

```
cyto = readtable('cytoband.csv');
rg = readtable('refgenes.csv');
rg_info = readtable('rg_info.csv');
```

Then, you can create a required **refgene.mat** file using [following command](https://www.mathworks.com/matlabcentral/answers/63201-creating-a-mat-file).

```
% create and save mm10.mat file
save mm10.mat cyto rg rg_info

% Clear separate files
clear cyto rg rg_info

% Load merged mm10.mat
load mm10.mat
```

***

**PS:** Once you have non-human genome refgene.mat file, you may need to re-compile `gp_gistic2_from_seg` executable as some of GISTCI2 source code files [2], e.g., _source/RefGeneInfo.m_ have hard-coded chromosomes for human genome. Checkout [README](https://github.com/sbamin/canine_gistic2) on how-to recompile `gp_gistic2_from_seg`.

1. ftp://ftp.broadinstitute.org/pub/GISTIC2.0/hg19.mat
2. ftp://ftp.broadinstitute.org/pub/GISTIC2.0/GISTIC_2_0_23.tar.gz

**Comment by monkeyBai96** [comment]
Could you share your mm10.mat ? Thank u so much !

**Comment by sbamin** [comment]
Sorry but I do not have mm10. See if you can email GISTIC team and hopefully they can build mm10.mat quickly.

**Comment by pangxueyu233** [comment]
Hi, 
I had generated the ```mm10.mat``` files as your recommendation. 
But I directly used the ```gp_gistic2_from_seg_upd``` files to execute the codes as following:
~~~R
MCRROOT=/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80
echo ---
LD_LIBRARY_PATH=.:${MCRROOT}/runtime/glnxa64 ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRROOT}/bin/glnxa64 ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRROOT}/sys/os/glnxa64;
MCRJRE=${MCRROOT}/sys/java/jre/glnxa64/jre/lib/amd64 ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/native_threads ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/server ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/client ;
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE} ;
XAPPLRESDIR=${MCRROOT}/X11/app-defaults ;
export LD_LIBRARY_PATH;
export XAPPLRESDIR;
echo LD_LIBRARY_PATH is ${LD_LIBRARY_PATH};

./gp_gistic2_from_seg_upd \
-b ./cnv/KO_VS_WT/gistic \
-seg ./cnv/KO_VS_WT/new_mouse_ALL_gistic.segments \
-mk ./cnv/KO_VS_WT/mouse_ALL_markerFiles.txt \
-refgene ./genome_index/bwa_index/bwa_mm10_index/mm10.mat \
-ta 0.1 \
-broad 1 \
-armpeel 0 \
-brlen 0.98 \
-conf 0.9 \
-td 0.1 \
-genegistic 1 \
-savegene 1
~~~
But, I met the errors as following:
~~~R
GISTIC version 2.0.22
Error using regexp
All cells must be strings.

Error in normalize_by_arm_length (line 45)

Error in make_sample_B (line 50)

Error in perform_deconstruction (line 68)

Error in perform_ziggurat_deconstruction (line 120)

Error in run_focal_gistic (line 156)

Error in run_gistic20 (line 127)

Error in run_gistic2_from_seg (line 225)

Error in gp_gistic2_from_seg (line 97)

MATLAB:REGEXP:invalidCellInputs
~~~
I'm a new hand in matlab, I guessed this error happened because I hadn't recompile the gp_gistic2_from_seg_upd files. Could you help us to recompile the ```gp_gistic2_from_seg_upd``` files for mouse data. I had provided the ```mm10.mat``` here. 

[mm10.zip](https://github.com/sbamin/canine_gistic2/files/7051592/mm10.zip)
