### ISSUE TITLE
locus information in the gtf file 

### ISSUE THREAD

**Issue by Anjaligarg006** [sbamin/canine_gistic2#8]
Hi, I am trying to build a new mat file but unable to find the locus information in the gtf file from ensemble. Can anyone help me with this?

Thank you so much!

**Comment by sbamin** [comment]
If you are looking for ideogram related locus info, you may contact Matthew Breen, https://www.breenlab.org as he published ideograms several years back for canfam 3.1. For the more recent version, Kerstin Lindblad-Toh's group should have that info. https://www.nature.com/articles/s42003-021-01698-x

**Comment by Anjaligarg006** [comment]
Thank you so much for the response. I am wondering what file you had use to build that canFam3.1 reference. It will be really grateful if you help me to locate that file, because I am able to find that. Any help much appreciated!

**Comment by sbamin** [comment]
Wish I could be of more help with gistic2. 

canFam3.1.fa was from https://may2021.archive.ensembl.org/Canis_lupus_familiaris/Info/Index but please know that since 2021, there are at least two major updates to dog reference genome with current version of Dog ref genome on Ensemble showing `ROS_Cfam_1.0 (GCA_014441545.1)`, https://useast.ensembl.org/Canis_lupus_familiaris/Info/Index
